#!/bin/sh

if which upsc > /dev/null 2>&1 ; then
    echo '<<<nut>>>'
    for ups in $(upsc -l > /dev/stdout 2> /dev/null)
    do
        upsc $ups > /dev/stdout 2> /dev/null | sed "s,^,$ups ,"
    done
fi
